import Dashboard from '@/components/Dashboard'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Slack App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className='dash'>
          <Dashboard />
          <div className='child'>
             {children}
            </div>
        </div>
        </body>
    </html>
  )
}
